source_object_type	source_object	source_field	target_object_type	target_object	target_field	relationship	line_no	line_content	persistent_impact_objects	intermediate_objects	confidence
VIEW_DDL	ddl_views.sql		VIEW	INTERFACE.V_API_MTM_REVAL		CREATE_VIEW	1	CREATE VIEW INTERFACE.V_API_MTM_REVAL AS			REGEX
VIEW_DDL	ddl_views.sql	CUSTOMER_NUMBER	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	CREATE_VIEW_MAP	3	    F.CUSTOMER_NUMBER AS CUST_NUM,	INTERFACE.V_API_MTM_REVAL.CUST_NUM		PARSER
VIEW_DDL	ddl_views.sql	DEAL_NUMBER	VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_NUM	CREATE_VIEW_MAP	4	    F.DEAL_NUMBER     AS DEAL_NUM,	INTERFACE.V_API_MTM_REVAL.DEAL_NUM		PARSER
VIEW_DDL	ddl_views.sql	DEAL_TYPE	VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_TYPE	CREATE_VIEW_MAP	5	    F.DEAL_TYPE       AS DEAL_TYPE,	INTERFACE.V_API_MTM_REVAL.DEAL_TYPE		PARSER
VIEW_DDL	ddl_views.sql	MTM_AMOUNT	VIEW	INTERFACE.V_API_MTM_REVAL	CUR_MTM_AMT	CREATE_VIEW_MAP	6	    F.MTM_AMOUNT      AS CUR_MTM_AMT,	INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT		PARSER
VIEW_DDL	ddl_views.sql	LAST_UPDATE_TS	VIEW	INTERFACE.V_API_MTM_REVAL	LAST_UPD_TS	CREATE_VIEW_MAP	7	    F.LAST_UPDATE_TS  AS LAST_UPD_TS	INTERFACE.V_API_MTM_REVAL.LAST_UPD_TS		PARSER
VIEW_DDL	ddl_views.sql		TABLE	FOS.API_MTM_REVAL		SELECT_TABLE	8	FROM FOS.API_MTM_REVAL F			PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_VALUE	TABLE	CCL.CODE_MAP	CODE_VALUE	SELECT_FIELD	16	        SELECT CODE_VALUE			PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE		TABLE	CCL.CODE_MAP		SELECT_TABLE	17	        FROM CCL.CODE_MAP			PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_CATEGORY	TABLE	CCL.CODE_MAP	CODE_CATEGORY	WHERE	18	        WHERE CODE_CATEGORY = P_CODE_CATEGORY			PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_SUB_CATEGORY	TABLE	CCL.CODE_MAP	CODE_SUB_CATEGORY	WHERE	19	          AND CODE_SUB_CATEGORY = P_CODE_SUB_CATEGORY			PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_TYPE	TABLE	CCL.CODE_MAP	CODE_TYPE	WHERE	20	          AND CODE_TYPE = P_CODE_TYPE			PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	KEY1	TABLE	CCL.CODE_MAP	KEY1	WHERE	21	          AND KEY1 = P_KEY1			PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	KEY2	TABLE	CCL.CODE_MAP	KEY2	WHERE	22	          AND KEY2 = P_KEY2			PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_VALUE	TABLE	CCL.CODE_MAP	CODE_VALUE	RETURN_VALUE	26	    RETURN COALESCE(V_RESULT, 'NA');		CCL.CODE_MAP.CODE_VALUE	PARSER
FUNCTION	INTERFACE.FN_REL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	SELECT_EXPR	12	        SELECT TRIM(V.CUST_NUM) || '-' ||			PARSER
FUNCTION	INTERFACE.FN_REL_DEMO		FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE		CALL_FUNCTION	13	               INTERFACE.FN_GET_CODE_MAP_VALUE('MTM','STATUS','DEFAULT','A','B')			PARSER
FUNCTION	INTERFACE.FN_REL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		SELECT_VIEW	14	        FROM INTERFACE.V_API_MTM_REVAL V			PARSER
FUNCTION	INTERFACE.FN_REL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	WHERE	15	        WHERE V.CUST_NUM = P_CUST_NUM			PARSER
FUNCTION	INTERFACE.FN_REL_DEMO	CUST_NUM	FUNCTION	INTERFACE.FN_REL_DEMO	RETURN_VALUE	RETURN_VALUE	19	    RETURN V_OUT;		INTERFACE.V_API_MTM_REVAL.CUST_NUM	PARSER
FUNCTION	INTERFACE.FN_REL_DEMO		FUNCTION	INTERFACE.FN_REL_DEMO	RETURN_VALUE	RETURN_VALUE	19	    RETURN V_OUT;		INTERFACE.FN_GET_CODE_MAP_VALUE	PARSER
PROCEDURE	EXTRA_PATTERNS	DEAL_TYPE	TABLE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	SELECT_FIELD	2	    I.DEAL_TYPE,			PARSER
PROCEDURE	EXTRA_PATTERNS		TABLE	INTERFACE.API_MTM_REVAL		SELECT_TABLE	4	FROM INTERFACE.API_MTM_REVAL I			PARSER
PROCEDURE	EXTRA_PATTERNS		TABLE	FOS.API_MTM_REVAL		SELECT_TABLE	5	JOIN FOS.API_MTM_REVAL F			PARSER
PROCEDURE	EXTRA_PATTERNS	DEAL_NUMBER	TABLE	FOS.API_MTM_REVAL	DEAL_NUMBER	JOIN_ON	6	  ON I.DEAL_NUM = F.DEAL_NUMBER			PARSER
PROCEDURE	EXTRA_PATTERNS	DEAL_NUM	TABLE	INTERFACE.API_MTM_REVAL	DEAL_NUM	JOIN_ON	6	  ON I.DEAL_NUM = F.DEAL_NUMBER			PARSER
PROCEDURE	EXTRA_PATTERNS	STATUS_CD	TABLE	INTERFACE.API_MTM_REVAL	STATUS_CD	WHERE	7	WHERE I.STATUS_CD = 'ACTIVE'			PARSER
PROCEDURE	EXTRA_PATTERNS	DEAL_TYPE	TABLE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	GROUP_BY	8	GROUP BY I.DEAL_TYPE			PARSER
PROCEDURE	EXTRA_PATTERNS		TABLE	INTERFACE.API_MTM_REVAL		HAVING	9	HAVING COUNT(*) > 1			PARSER
PROCEDURE	EXTRA_PATTERNS	DEAL_TYPE	TABLE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	ORDER_BY	10	ORDER BY I.DEAL_TYPE			PARSER
PROCEDURE	EXTRA_PATTERNS		UNKNOWN	UNKNOWN_DYNAMIC_SQL		UNKNOWN	13	EXECUTE IMMEDIATE 'DELETE FROM INTERFACE.API_MTM_REVAL WHERE STATUS_CD = ''X'''			DYNAMIC_LOW_CONFIDENCE
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		CREATE_TABLE	10	    DECLARE GLOBAL TEMPORARY TABLE SESSION.T_MTM_STAGE			REGEX
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL		CREATE_TABLE	20	    DECLARE GLOBAL TEMPORARY TABLE SESSION.T_MTM_STAGE_ALL			REGEX
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		FUNCTION	INTERFACE.FN_REL_DEMO		CALL_FUNCTION	30	    SET V_STATUS = INTERFACE.FN_REL_DEMO(P_CUST_NUM);			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		INSERT_TABLE	32	    INSERT INTO SESSION.T_MTM_STAGE			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		CTE	BASE_DATA		CTE_DEFINE	39	    WITH BASE_DATA AS		BASE_DATA	REGEX
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	SELECT_FIELD	42	            V.CUST_NUM,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_NUM	SELECT_FIELD	43	            V.DEAL_NUM,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_TYPE	SELECT_FIELD	44	            V.DEAL_TYPE,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	VIEW	INTERFACE.V_API_MTM_REVAL	CUR_MTM_AMT	SELECT_FIELD	45	            V.CUR_MTM_AMT			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		UNION_INPUT	46	        FROM INTERFACE.V_API_MTM_REVAL V		BASE_DATA	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	WHERE	47	        WHERE V.CUST_NUM = P_CUST_NUM			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	TABLE	INTERFACE.API_MTM_REVAL	CUST_NUM	SELECT_FIELD	52	            I.CUST_NUM,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	TABLE	INTERFACE.API_MTM_REVAL	DEAL_NUM	SELECT_FIELD	53	            I.DEAL_NUM,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	TABLE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	SELECT_FIELD	54	            I.DEAL_TYPE,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	TABLE	INTERFACE.API_MTM_REVAL	CUR_MTM_AMT	SELECT_FIELD	55	            I.CUR_MTM_AMT			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		UNION_INPUT	56	        FROM INTERFACE.API_MTM_REVAL I		BASE_DATA	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	TABLE	INTERFACE.API_MTM_REVAL	CUST_NUM	WHERE	57	        WHERE I.CUST_NUM = P_CUST_NUM			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	CTE	BASE_DATA	CUST_NUM	INSERT_SELECT_MAP	60	        B.CUST_NUM,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	CTE	BASE_DATA	DEAL_NUM	INSERT_SELECT_MAP	61	        B.DEAL_NUM,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	CTE	BASE_DATA	DEAL_TYPE	INSERT_SELECT_MAP	62	        B.DEAL_TYPE,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	CTE	BASE_DATA	CUR_MTM_AMT	INSERT_SELECT_MAP	63	        B.CUR_MTM_AMT			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	CTE	BASE_DATA	CUST_NUM	CTE_READ	64	    FROM BASE_DATA B;		BASE_DATA.CUST_NUM	REGEX
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL		INSERT_TABLE	66	    INSERT INTO SESSION.T_MTM_STAGE_ALL			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	CUST_NUM	INSERT_SELECT_MAP	74	        S.CUST_NUM,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_NUM	INSERT_SELECT_MAP	75	        S.DEAL_NUM,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_TYPE	INSERT_SELECT_MAP	76	        S.DEAL_TYPE,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	INSERT_SELECT_MAP	77	        S.CUR_MTM_AMT			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		SELECT_TABLE	78	    FROM SESSION.T_MTM_STAGE S;			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		INSERT_TABLE	80	    INSERT INTO INTERFACE.API_MTM_REVAL			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	CUST_NUM	INSERT_TARGET_COL	82	        CUST_NUM,	INTERFACE.API_MTM_REVAL.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	DEAL_NUM	INSERT_TARGET_COL	83	        DEAL_NUM,	INTERFACE.API_MTM_REVAL.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	INSERT_TARGET_COL	84	        DEAL_TYPE,	INTERFACE.API_MTM_REVAL.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	CUR_MTM_AMT	INSERT_TARGET_COL	85	        CUR_MTM_AMT,	INTERFACE.API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	STATUS_CD	INSERT_TARGET_COL	86	        STATUS_CD,	INTERFACE.API_MTM_REVAL.STATUS_CD		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	LAST_UPD_TS	INSERT_TARGET_COL	87	        LAST_UPD_TS	INTERFACE.API_MTM_REVAL.LAST_UPD_TS		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	CUST_NUM	INSERT_SELECT_MAP	90	        S.CUST_NUM,	INTERFACE.API_MTM_REVAL.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_NUM	INSERT_SELECT_MAP	91	        S.DEAL_NUM,	INTERFACE.API_MTM_REVAL.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_TYPE	INSERT_SELECT_MAP	92	        S.DEAL_TYPE,	INTERFACE.API_MTM_REVAL.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	INSERT_SELECT_MAP	93	        S.CUR_MTM_AMT,	INTERFACE.API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		SELECT_TABLE	96	    FROM SESSION.T_MTM_STAGE S;			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL_STAR		INSERT_TABLE	98	    INSERT INTO INTERFACE.API_MTM_REVAL_STAR			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL_STAR	CUR_MTM_AMT	INSERT_TARGET_COL	98	INFERRED TARGET COLUMN FROM METADATA: CUR_MTM_AMT	INTERFACE.API_MTM_REVAL_STAR.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL_STAR	CUST_NUM	INSERT_TARGET_COL	98	INFERRED TARGET COLUMN FROM METADATA: CUST_NUM	INTERFACE.API_MTM_REVAL_STAR.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL_STAR	DEAL_NUM	INSERT_TARGET_COL	98	INFERRED TARGET COLUMN FROM METADATA: DEAL_NUM	INTERFACE.API_MTM_REVAL_STAR.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL_STAR	DEAL_TYPE	INSERT_TARGET_COL	98	INFERRED TARGET COLUMN FROM METADATA: DEAL_TYPE	INTERFACE.API_MTM_REVAL_STAR.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	CUR_MTM_AMT	INSERT_SELECT_MAP	99	    SELECT *	INTERFACE.API_MTM_REVAL_STAR.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	CUST_NUM	INSERT_SELECT_MAP	99	    SELECT *	INTERFACE.API_MTM_REVAL_STAR.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	DEAL_NUM	INSERT_SELECT_MAP	99	    SELECT *	INTERFACE.API_MTM_REVAL_STAR.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	DEAL_TYPE	INSERT_SELECT_MAP	99	    SELECT *	INTERFACE.API_MTM_REVAL_STAR.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL		SELECT_TABLE	100	    FROM SESSION.T_MTM_STAGE_ALL;			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		INSERT_VIEW	102	    INSERT INTO INTERFACE.V_API_MTM_REVAL			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	INSERT_TARGET_COL	104	        CUST_NUM,	INTERFACE.V_API_MTM_REVAL.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_NUM	INSERT_TARGET_COL	105	        DEAL_NUM,	INTERFACE.V_API_MTM_REVAL.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_TYPE	INSERT_TARGET_COL	106	        DEAL_TYPE,	INTERFACE.V_API_MTM_REVAL.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL	CUR_MTM_AMT	INSERT_TARGET_COL	107	        CUR_MTM_AMT,	INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL	LAST_UPD_TS	INSERT_TARGET_COL	108	        LAST_UPD_TS	INTERFACE.V_API_MTM_REVAL.LAST_UPD_TS		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUSTOMER_NUMBER	TABLE	FOS.API_MTM_REVAL	CUSTOMER_NUMBER	INSERT_SELECT_MAP	111	        CUSTOMER_NUMBER,	INTERFACE.V_API_MTM_REVAL.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUSTOMER_NUMBER	TABLE	FOS.API_MTM_REVAL	CUSTOMER_NUMBER	SELECT_FIELD	111	        CUSTOMER_NUMBER,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUMBER	TABLE	FOS.API_MTM_REVAL	DEAL_NUMBER	INSERT_SELECT_MAP	112	        DEAL_NUMBER,	INTERFACE.V_API_MTM_REVAL.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUMBER	TABLE	FOS.API_MTM_REVAL	DEAL_NUMBER	SELECT_FIELD	112	        DEAL_NUMBER,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	TABLE	FOS.API_MTM_REVAL	DEAL_TYPE	INSERT_SELECT_MAP	113	        DEAL_TYPE,	INTERFACE.V_API_MTM_REVAL.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	TABLE	FOS.API_MTM_REVAL	DEAL_TYPE	SELECT_FIELD	113	        DEAL_TYPE,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	MTM_AMOUNT	TABLE	FOS.API_MTM_REVAL	MTM_AMOUNT	INSERT_SELECT_MAP	114	        MTM_AMOUNT,	INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	MTM_AMOUNT	TABLE	FOS.API_MTM_REVAL	MTM_AMOUNT	SELECT_FIELD	114	        MTM_AMOUNT,			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	LAST_UPDATE_TS	TABLE	FOS.API_MTM_REVAL	LAST_UPDATE_TS	INSERT_SELECT_MAP	115	        LAST_UPDATE_TS	INTERFACE.V_API_MTM_REVAL.LAST_UPD_TS		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	LAST_UPDATE_TS	TABLE	FOS.API_MTM_REVAL	LAST_UPDATE_TS	SELECT_FIELD	115	        LAST_UPDATE_TS			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	FOS.API_MTM_REVAL		SELECT_TABLE	116	    FROM FOS.API_MTM_REVAL			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUSTOMER_NUMBER	TABLE	FOS.API_MTM_REVAL	CUSTOMER_NUMBER	WHERE	117	    WHERE CUSTOMER_NUMBER = P_CUST_NUM;			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		UPDATE_TABLE	119	    UPDATE INTERFACE.API_MTM_REVAL T			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	STATUS_CD	UPDATE_TARGET_COL	120	       SET STATUS_CD = 'ACTIVE',	INTERFACE.API_MTM_REVAL.STATUS_CD		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	CUR_MTM_AMT	UPDATE_TARGET_COL	121	           CUR_MTM_AMT = (	INTERFACE.API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	UPDATE_SET	122	               SELECT S.CUR_MTM_AMT			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	UPDATE_SET_MAP	122	               SELECT S.CUR_MTM_AMT	INTERFACE.API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		SELECT_TABLE	123	               FROM SESSION.T_MTM_STAGE S			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	TABLE	INTERFACE.API_MTM_REVAL	CUST_NUM	WHERE	127	     WHERE T.CUST_NUM = P_CUST_NUM;			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		UPDATE_VIEW	129	    UPDATE INTERFACE.V_API_MTM_REVAL V			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_TYPE	UPDATE_TARGET_COL	130	       SET DEAL_TYPE = 'UPD'	INTERFACE.V_API_MTM_REVAL.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	WHERE	131	     WHERE V.CUST_NUM = P_CUST_NUM;			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		DELETE_TABLE	133	    DELETE FROM INTERFACE.API_MTM_REVAL			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	STATUS_CD	TABLE	INTERFACE.API_MTM_REVAL	STATUS_CD	WHERE	134	     WHERE STATUS_CD = 'OLD';			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		DELETE_VIEW	136	    DELETE FROM INTERFACE.V_API_MTM_REVAL			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	WHERE	137	     WHERE CUST_NUM = 'TO_DELETE';			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		MERGE_TABLE	139	    MERGE INTO INTERFACE.API_MTM_REVAL T			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		SELECT_TABLE	140	    USING SESSION.T_MTM_STAGE S			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	TABLE	INTERFACE.API_MTM_REVAL	DEAL_NUM	MERGE_MATCH	141	       ON T.DEAL_NUM = S.DEAL_NUM			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	MERGE_SET_MAP	144	             T.CUR_MTM_AMT = S.CUR_MTM_AMT,	INTERFACE.API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	CUR_MTM_AMT	MERGE_TARGET_COL	144	             T.CUR_MTM_AMT = S.CUR_MTM_AMT,	INTERFACE.API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL	STATUS_CD	MERGE_TARGET_COL	145	             T.STATUS_CD = 'MERGED'	INTERFACE.API_MTM_REVAL.STATUS_CD		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	CUST_NUM	MERGE_INSERT_MAP	158	             S.CUST_NUM,	INTERFACE.API_MTM_REVAL.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_NUM	MERGE_INSERT_MAP	159	             S.DEAL_NUM,	INTERFACE.API_MTM_REVAL.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_TYPE	MERGE_INSERT_MAP	160	             S.DEAL_TYPE,	INTERFACE.API_MTM_REVAL.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	MERGE_INSERT_MAP	161	             S.CUR_MTM_AMT,	INTERFACE.API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		MERGE_VIEW	166	    MERGE INTO INTERFACE.V_API_MTM_REVAL V			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		SELECT_TABLE	167	    USING SESSION.T_MTM_STAGE S			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_NUM	MERGE_MATCH	168	       ON V.DEAL_NUM = S.DEAL_NUM			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	MERGE_SET_MAP	171	             V.CUR_MTM_AMT = S.CUR_MTM_AMT	INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL	CUR_MTM_AMT	MERGE_TARGET_COL	171	             V.CUR_MTM_AMT = S.CUR_MTM_AMT	INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	CUST_NUM	MERGE_INSERT_MAP	183	             S.CUST_NUM,	INTERFACE.V_API_MTM_REVAL.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_NUM	MERGE_INSERT_MAP	184	             S.DEAL_NUM,	INTERFACE.V_API_MTM_REVAL.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_TYPE	MERGE_INSERT_MAP	185	             S.DEAL_TYPE,	INTERFACE.V_API_MTM_REVAL.DEAL_TYPE		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	MERGE_INSERT_MAP	186	             S.CUR_MTM_AMT,	INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		CALL_PROCEDURE	190	    CALL RPT.PR_AUDIT_MTM_REVAL(P_CUST_NUM, 'D001', 'DONE');			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.MTM_REVAL_TMP_COPY		INSERT_TABLE	192	    INSERT INTO INTERFACE.MTM_REVAL_TMP_COPY			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.MTM_REVAL_TMP_COPY	CUST_NUM	INSERT_TARGET_COL	194	        CUST_NUM,	INTERFACE.MTM_REVAL_TMP_COPY.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.MTM_REVAL_TMP_COPY	DEAL_NUM	INSERT_TARGET_COL	195	        DEAL_NUM,	INTERFACE.MTM_REVAL_TMP_COPY.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.MTM_REVAL_TMP_COPY	CUR_MTM_AMT	INSERT_TARGET_COL	196	        CUR_MTM_AMT	INTERFACE.MTM_REVAL_TMP_COPY.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	TABLE	INTERFACE.API_MTM_REVAL	CUST_NUM	INSERT_SELECT_MAP	199	        CUST_NUM,	INTERFACE.MTM_REVAL_TMP_COPY.CUST_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	TABLE	INTERFACE.API_MTM_REVAL	DEAL_NUM	INSERT_SELECT_MAP	200	        DEAL_NUM,	INTERFACE.MTM_REVAL_TMP_COPY.DEAL_NUM		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	TABLE	INTERFACE.API_MTM_REVAL	CUR_MTM_AMT	INSERT_SELECT_MAP	201	        CUR_MTM_AMT	INTERFACE.MTM_REVAL_TMP_COPY.CUR_MTM_AMT		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		SELECT_TABLE	202	    FROM INTERFACE.API_MTM_REVAL;			PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.MTM_REVAL_HIST		TRUNCATE_TABLE	204	    TRUNCATE TABLE INTERFACE.MTM_REVAL_HIST IMMEDIATE;			REGEX
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		SESSION_TABLE	SESSION.T_GRAPH_STAGE		CREATE_TABLE	5	    DECLARE GLOBAL TEMPORARY TABLE SESSION.T_GRAPH_STAGE			REGEX
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_A		INSERT_TABLE	12	    INSERT INTO TABLE_A			PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_A	COL_A	INSERT_TARGET_COL	14	        COL_A	TABLE_A.COL_A		PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO	COL_A	SESSION_TABLE	SESSION.T_GRAPH_STAGE	COL_A	INSERT_SELECT_MAP	17	        S.COL_A	TABLE_A.COL_A		PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		SESSION_TABLE	SESSION.T_GRAPH_STAGE		SELECT_TABLE	18	    FROM SESSION.T_GRAPH_STAGE S;			PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_B		INSERT_TABLE	20	    INSERT INTO TABLE_B			PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_B	COL_B	INSERT_TARGET_COL	22	        COL_B	TABLE_B.COL_B		PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO	COL_A	SESSION_TABLE	SESSION.T_GRAPH_STAGE	COL_A	INSERT_SELECT_MAP	25	        S.COL_A	TABLE_B.COL_B		PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		SESSION_TABLE	SESSION.T_GRAPH_STAGE		SELECT_TABLE	26	    FROM SESSION.T_GRAPH_STAGE S;			PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_C		INSERT_TABLE	28	    INSERT INTO TABLE_C			PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_C	COL_C	INSERT_TARGET_COL	30	        COL_C	TABLE_C.COL_C		PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO	COL_A	TABLE	TABLE_A	COL_A	INSERT_SELECT_MAP	33	        A.COL_A	TABLE_C.COL_C		PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_A		SELECT_TABLE	34	    FROM TABLE_A A;			PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_B		INSERT_TABLE	36	    INSERT INTO TABLE_B			PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO	COL_C	TABLE	TABLE_C	COL_C	INSERT_SELECT_MAP	41	        C.COL_C	TABLE_B.COL_B		PARSER
PROCEDURE	INTERFACE.PI_GRAPH_DEMO		TABLE	TABLE_C		SELECT_TABLE	42	    FROM TABLE_C C;			PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT		INSERT_TABLE	10	    INSERT INTO RPT.MTM_REVAL_AUDIT			PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	AUDIT_ID	INSERT_TARGET_COL	12	        AUDIT_ID,	RPT.MTM_REVAL_AUDIT.AUDIT_ID		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	CUST_NUM	INSERT_TARGET_COL	13	        CUST_NUM,	RPT.MTM_REVAL_AUDIT.CUST_NUM		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	DEAL_NUM	INSERT_TARGET_COL	14	        DEAL_NUM,	RPT.MTM_REVAL_AUDIT.DEAL_NUM		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	ACTION_CD	INSERT_TARGET_COL	15	        ACTION_CD,	RPT.MTM_REVAL_AUDIT.ACTION_CD		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	AUDIT_TS	INSERT_TARGET_COL	16	        AUDIT_TS	RPT.MTM_REVAL_AUDIT.AUDIT_TS		PARSER
