CREATE OR REPLACE PROCEDURE INTERFACE.PR_TRANSFORM_GM_COMMON_FIXING_DEAL()
SPECIFIC PR_TRANSFORM_GM_COMMON_FIXING_DEAL
LANGUAGE SQL

BEGIN

    DECLARE SQLCODE             INT DEFAULT 0;
    DECLARE ld_message_text     VARCHAR(512);
    DECLARE ld_err_pos          VARCHAR(1000);
    DECLARE ld_error_message    VARCHAR(512);
    DECLARE ld_procedure_name   VARCHAR(100) DEFAULT 'INTERFACE.PR_TRANSFORM_GM_COMMON_FIXING_DEAL';
    DECLARE ld_last_biz_date    DATE;
    DECLARE ld_biz_date         DATE;
    DECLARE ls_local_ccy_code   VARCHAR(3);
    DECLARE ls_region_code      VARCHAR(3);

    -- SUPPLEMENTED/DB2_SYNTAX_FIX: exception handler reconstructed from sibling procedure style; required for complete SQL PL block.
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS EXCEPTION 1 ld_message_text = MESSAGE_TEXT;

        COMMIT;
        VALUES (ld_procedure_name || ' failed. ' || ld_err_pos || '. Details: ' || ld_message_text) INTO ld_error_message;
        IF (SUBSTR(ld_message_text, 1, 8) <> 'SQL0438N') THEN
            CALL INTERFACE.PR_PROCEDURE_LOG('GENERIC_MEMO_TRANSFORM', ld_procedure_name, 'ERROR', ld_error_message);
            COMMIT;
        END IF;
        RESIGNAL SQLSTATE '88888';
    END;

    -- SUPPLEMENTED/DB2_SYNTAX_FIX: procedure setup reconstructed from visible sibling procedure and variables referenced in screenshots.
    CALL INTERFACE.PR_PROCEDURE_LOG('GENERIC_MEMO_TRANSFORM', ld_procedure_name, 'INFO', 'Start insert data to INTERFACE.GM_COMMON_FIXING_DEAL');

    SELECT LAST_BUS_DT, BUS_DT, REGION_CDE
      INTO ld_last_biz_date, ld_biz_date, ls_region_code
      FROM INTERFACE.SYS
     WHERE SYS_CDE = 'EFOS';

    SET ls_local_ccy_code = INTERFACE.FN_GET_LOCAL_CURRENCY();

    IF EXISTS ( SELECT 1 FROM INTERFACE.GM_COMMON_FIXING_DEAL FETCH FIRST 1 ROW ONLY ) THEN
        DELETE FROM INTERFACE.GM_COMMON_FIXING_DEAL;
    END IF;

    SET ld_err_pos = 'Position: insert client data to INTERFACE.GM_COMMON_FIXING_DEAL ';
    INSERT INTO INTERFACE.GM_COMMON_FIXING_DEAL
    (
        ACTV_FLAG
        ,DEAL_NUM
        ,DEAL_SB_NUM

    ,DEAL_COMP_CDE
    ,DEAL_BRNCH_CDE
    ,DEAL_TRAN_TYPE
    ,CUST_NUM
    ,SB_ACCT_NUM
    ,DEAL_TYPE
    ,PROD_TYPE
    ,ASSET_CLASS
    ,BANK_CUST_FLAG
    ,FIXING_EVENT_TYPE
    ,START_DT
    ,END_DT
    ,CASH_SETL_FLAG
    ,INT_RATE
    ,PAY_RECEIVE_FLAG
    ,SETL_DT
    ,SETL_CCY
    ,SETL_AMT
    ,BUY_CCY
    ,BUY_AMT
    ,MRK_RECV_SETL_DT
    ,SELL_CCY
    ,SELL_AMT
    ,MRK_PAY_SETL_DT
    ,CROS_DEAL_NUM
    ,CROS_DEAL_SB_NUM
    ,LINK_DEAL_TYPE
    ,LINK_DEAL_NUMBER
    ,LINK_DEAL_SUB_NUMBER
    ,CREAT_TS
    ,RVRSE_TS
    ,UPDT_TS
)
select
    PAYMENT.ACTIVE_FLAG                                      AS ACTV_FLAG
    ,PAYMENT.NMEMO_DEAL_NUMBER                              AS DEAL_NUM        --fixing
    ,PAYMENT.NMEMO_DEAL_SUB_NUMBER                          AS DEAL_SB_NUM
    --,PAYMENT.DEAL_COMPANY_CODE                            AS DEAL_COMP_CDE
    --,PAYMENT.DEAL_BRANCH_CODE                             AS DEAL_BRNCH_CDE
    ,CASE WHEN ls_region_code = 'SG' THEN '68' WHEN ls_region_code = 'HK' THEN '63' END AS DEAL_COMP_CDE --Amended by Nancy on 04Jan2021
    ,CASE WHEN ls_region_code = 'SG' THEN
        CASE WHEN (ls_local_ccy_code = PAYMENT.PAY_CURRENCY_CODE OR ls_local_ccy_code = PAYMENT.RECEIVE_CURRENCY_CODE) THEN '02' ELSE '03' END
        WHEN ls_region_code = 'HK' THEN '02' END             AS DEAL_BRNCH_CDE --Amended by Nancy on 04Jan2021
    ,DEAL.DEAL_TRANSACTION_TYPE                              AS DEAL_TRAN_TYPE --'F'
    ,PAYMENT.CUSTOMER_NUMBER                                 AS CUST_NUM
    ,PAYMENT.SUB_ACCOUNT_NUMBER                              AS SB_ACCT_NUM
    ,'MM'                                                    AS PROD_TYPE
    ,'MM'                                                    AS DEAL_TYPE
    --,CASE WHEN NMEMO_TEMPLATE.ASSET_TYPE IN ('FX','EQ','FI','IR','CD') THEN NMEMO_TEMPLATE.ASSET_TYPE
    ,CASE WHEN NMEMO_TEMPLATE.ASSET_TYPE IN ('FX','EQ','FI','IR','CT') THEN NMEMO_TEMPLATE.ASSET_TYPE --Amend by Allen on 23Oct2020
          WHEN NMEMO_TEMPLATE.ASSET_TYPE IN ('NX') THEN 'EQ'
          WHEN NMEMO_TEMPLATE.ASSET_TYPE IN ('CD') THEN 'CT' --Add by Allen on 23Oct2020
          ELSE 'MX'
     END                                                     AS ASSET_CLASS
    ,'C'                                                     AS BANK_CUST_FLAG --Client
    ,PAYMENT.FIXING_EVENT_TYPE                               AS FIXING_EVENT_TYPE
    ,PAYMENT.PERIOD_START_DATE                               AS START_DT
    ,PAYMENT.FIXING_DATE                                     AS END_DT
    ,CASE WHEN NMEMO_TEMPLATE.NMEMO_SETTLEMENT_TYPE = 'CASH' THEN 'Y' ELSE 'N' END AS CASH_SETL_FLAG
    ,COALESCE(NLU.UNDERLYING_INITIAL_SPOT,0)                 AS INT_RATE
    ,CASE WHEN COALESCE(PAYMENT.PAY_AMOUNT,0) > 0 AND PAYMENT.RECEIVE_AMOUNT IS NULL THEN 'P'     --client pay,bank rec
          WHEN COALESCE(PAYMENT.RECEIVE_AMOUNT,0) > 0 AND PAYMENT.PAY_AMOUNT IS NULL THEN 'R'     --client rec,bank pay
          ELSE '' END                                        AS PAY_RECEIVE_FLAG --bank view
    ,PAYMENT.SETTLE_DATE                                     AS SETL_DT
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NULL THEN COALESCE(PAYMENT.PAY_CURRENCY_CODE, PAYMENT.RECEIVE_CURRENCY_CODE) END AS SETL_CCY
    --[Amended by Jing on 23Jun2022 begin hot fix to long term fix
    --,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NULL THEN COALESCE(PAYMENT.PAY_AMOUNT,PAYMENT.RECEIVE_AMOUNT,0) END AS SETL_AMT
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NULL THEN COALESCE(PAYMENT.PAY_AMOUNT,PAYMENT.RECEIVE_AMOUNT,0) ELSE 0 END AS SETL_AMT
    --Amended by Jing on 23Jun2022 end]
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN PAYMENT.RECEIVE_CURRENCY_CODE END AS BUY_CCY
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN COALESCE(PAYMENT.RECEIVE_AMOUNT,0) END AS BUY_AMT
    ,PAYMENT.RECEIVE_MARK_SETTLE_DATE                        AS MRK_RECV_SETL_DT
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN PAYMENT.PAY_CURRENCY_CODE END AS SELL_CCY
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN COALESCE(PAYMENT.PAY_AMOUNT,0) END AS SELL_AMT
    ,PAYMENT.PAY_MARK_SETTLE_DATE                            AS MRK_PAY_SETL_DT
    ,PAYMENT.DEAL_NUMBER                                     AS CROS_DEAL_NUM --original
    ,PAYMENT.DEAL_SUB_NUMBER                                 AS CROS_DEAL_SB_NUM
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN '51'
          WHEN PAYMENT.SHARE_DEAL_NUMBER IS NOT NULL THEN '76'
          WHEN (PAYMENT.PAY_DEAL_NUMBER IS NOT NULL OR PAYMENT.RECEIVE_DEAL_NUMBER IS NOT NULL) THEN '04'
          ELSE ''
     END                                                     AS LINK_DEAL_TYPE
    ,COALESCE(PAYMENT.FX_DEAL_NUMBER,PAYMENT.SHARE_DEAL_NUMBER,PAYMENT.PAY_DEAL_NUMBER,PAYMENT.RECEIVE_DEAL_NUMBER) AS LINK_DEAL_NUMBER
    ,COALESCE(PAYMENT.FX_DEAL_SUB_NUMBER,PAYMENT.SHARE_DEAL_SUB_NUMBER,PAYMENT.PAY_DEAL_SUB_NUMBER,PAYMENT.RECEIVE_DEAL_SUB_NUMBER) AS LINK_DEAL_SUB_NUMBER
    ,PAYMENT.CREATE_TIMESTAMP                                AS CREAT_TS
    ,PAYMENT.REVERSE_TIMESTAMP                               AS RVRSE_TS
    ,PAYMENT.UPDATE_TIMESTAMP                                AS UPDT_TS
FROM FOS.NMEMO_PAYMENT PAYMENT
JOIN FOS.NMEMO_DEAL DEAL --primary key (CUSTOMER_NUMBER,SUB_ACCOUNT_NUMBER,PRODUCT_TYPE,DEAL_NUMBER,DEAL_SUB_NUMBER)
    ON PAYMENT.CUSTOMER_NUMBER     = DEAL.CUSTOMER_NUMBER
   AND PAYMENT.SUB_ACCOUNT_NUMBER  = DEAL.SUB_ACCOUNT_NUMBER
   AND PAYMENT.PRODUCT_TYPE        = DEAL.PRODUCT_TYPE
   AND PAYMENT.DEAL_NUMBER         = DEAL.DEAL_NUMBER
   AND PAYMENT.DEAL_SUB_NUMBER     = DEAL.DEAL_SUB_NUMBER
JOIN FOS.NMEMO_TEMPLATE NMEMO_TEMPLATE
    ON NMEMO_TEMPLATE.NMEMO_ISSUE_CODE = DEAL.NMEMO_ISSUE_CODE
LEFT JOIN FOS.NMEMO_LEG_UNDERLYING NLU
    ON NMEMO_TEMPLATE.NMEMO_ISSUE_CODE = NLU.NMEMO_ISSUE_CODE
   AND NLU.UNDERLYING_CLASS_CODE = 'IR'
   AND NLU.UNDERLYING_ISSUE_CODE = 'FIX'
JOIN (
    SELECT ROW_NUMBER() OVER (
               PARTITION BY CUSTOMER_NUMBER,SUB_ACCOUNT_NUMBER,PRODUCT_TYPE,DEAL_NUMBER,DEAL_SUB_NUMBER,CREATE_DATE
               ORDER BY FIXING_DATE DESC, COALESCE(REMAINING_SETTLEMENT_NOTIONAL,0) ASC, FIXING_EVENT_TYPE
           ) AS ROW_NUM,
           CUSTOMER_NUMBER,SUB_ACCOUNT_NUMBER,PRODUCT_TYPE,DEAL_NUMBER,DEAL_SUB_NUMBER,CREATE_DATE,FIXING_DATE,FIXING_EVENT_TYPE
    FROM FOS.NMEMO_PAYMENT
    WHERE REVERSE_TIMESTAMP IS NULL
      AND CREATE_DATE > FIXING_DATE
      AND STATUS_FLAG IN ('CONFIRMED','PREV')
) FIXING --handle sameday multiple fixing
    ON PAYMENT.CUSTOMER_NUMBER    = FIXING.CUSTOMER_NUMBER
   AND PAYMENT.SUB_ACCOUNT_NUMBER = FIXING.SUB_ACCOUNT_NUMBER
   AND PAYMENT.PRODUCT_TYPE       = FIXING.PRODUCT_TYPE
   AND PAYMENT.DEAL_NUMBER        = FIXING.DEAL_NUMBER
   AND PAYMENT.DEAL_SUB_NUMBER    = FIXING.DEAL_SUB_NUMBER
   AND PAYMENT.FIXING_DATE        = FIXING.FIXING_DATE
   AND PAYMENT.FIXING_EVENT_TYPE  = FIXING.FIXING_EVENT_TYPE
   AND FIXING.ROW_NUM             = 1
WHERE PAYMENT.ACTIVE_FLAG = 'A'
  AND NMEMO_TEMPLATE.ACTIVE_FLAG = 'A'
  AND PAYMENT.STATUS_FLAG IN ('CONFIRMED','PREV');

-- broker side
SET ld_err_pos = 'Position: insert broker data to INTERFACE.GM_COMMON_FIXING_DEAL ';
INSERT INTO INTERFACE.GM_COMMON_FIXING_DEAL
(
    ACTV_FLAG
    ,DEAL_NUM
    ,DEAL_SB_NUM
    ,DEAL_COMP_CDE
    ,DEAL_BRNCH_CDE
    ,DEAL_TRAN_TYPE
    ,CUST_NUM
    ,SB_ACCT_NUM
    ,DEAL_TYPE
    ,PROD_TYPE
    ,ASSET_CLASS
    ,BANK_CUST_FLAG
    ,FIXING_EVENT_TYPE
    ,START_DT
    ,END_DT
    ,CASH_SETL_FLAG
    ,INT_RATE
    ,PAY_RECEIVE_FLAG
    ,SETL_DT
    ,SETL_CCY
    ,SETL_AMT
    ,BUY_CCY
    ,BUY_AMT
    ,MRK_RECV_SETL_DT
    ,SELL_CCY
    ,SELL_AMT
    ,MRK_PAY_SETL_DT
    ,CROS_DEAL_NUM
    ,CROS_DEAL_SB_NUM
    ,LINK_DEAL_TYPE
    ,LINK_DEAL_NUMBER
    ,LINK_DEAL_SUB_NUMBER
    ,CREAT_TS
    ,RVRSE_TS
    ,UPDT_TS
    ,PAY_OUR_NOSTRO_NUMBER
    ,RECEIVE_OUR_NOSTRO_NUMBER
    ,PAY_THEIR_NOSTRO_NUMBER
    ,RECEIVE_THEIR_NOSTRO_NUMBER
)
select
    PAYMENT.ACTIVE_FLAG                                      AS ACTV_FLAG
    ,PAYMENT.NMEMO_BANK_DEAL_NUMBER                         AS DEAL_NUM
    ,PAYMENT.NMEMO_BANK_DEAL_SUB_NUMBER                     AS DEAL_SB_NUM
    ,CASE WHEN ls_region_code = 'SG' THEN '68' WHEN ls_region_code = 'HK' THEN '63' END AS DEAL_COMP_CDE
    ,CASE WHEN ls_region_code = 'SG' THEN
        CASE WHEN ls_local_ccy_code = NMEMO_TEMPLATE.SETTLEMENT_CURRENCY THEN '02' ELSE '03' END -- DB2_SYNTAX_FIX: removed unmatched '(' from OCR
        WHEN ls_region_code = 'HK' THEN '02' END             AS DEAL_BRNCH_CDE --Amended by Nancy on 04Jan2021
    ,DEAL.DEAL_TRANSACTION_TYPE                              AS DEAL_TRAN_TYPE --'F'
    ,PAYMENT.BROKER_NUMBER                                   AS CUST_NUM
    ,'0001'                                                  AS SB_ACCT_NUM
    ,'MM'                                                    AS PROD_TYPE
    ,'MM'                                                    AS DEAL_TYPE
    --,CASE WHEN NMEMO_TEMPLATE.ASSET_TYPE IN ('FX','EQ','FI','IR','CD') THEN NMEMO_TEMPLATE.ASSET_TYPE
    ,CASE WHEN NMEMO_TEMPLATE.ASSET_TYPE IN ('FX','EQ','FI','IR','CT') THEN NMEMO_TEMPLATE.ASSET_TYPE --Amend by Allen on 23Oct2020
          WHEN NMEMO_TEMPLATE.ASSET_TYPE IN ('NX') THEN 'EQ'
          WHEN NMEMO_TEMPLATE.ASSET_TYPE IN ('CD') THEN 'CT' --Add by Allen on 23Oct2020
          ELSE 'MX'
     END                                                     AS ASSET_CLASS
    ,'B'                                                     AS BANK_CUST_FLAG --Bank
    ,PAYMENT.FIXING_EVENT_TYPE                               AS FIXING_EVENT_TYPE
    ,PAYMENT.PERIOD_START_DATE                               AS START_DT
    ,PAYMENT.FIXING_DATE                                     AS END_DT
    ,CASE WHEN NMEMO_TEMPLATE.NMEMO_SETTLEMENT_TYPE = 'CASH' THEN 'Y' ELSE 'N' END AS CASH_SETL_FLAG
    ,COALESCE(NLU.UNDERLYING_INITIAL_SPOT,0)                 AS INT_RATE
    ,CASE WHEN COALESCE(PAYMENT.PAY_AMOUNT,0) > 0 AND PAYMENT.RECEIVE_AMOUNT IS NULL THEN 'P'
          WHEN COALESCE(PAYMENT.RECEIVE_AMOUNT,0) > 0 AND PAYMENT.PAY_AMOUNT IS NULL THEN 'R'
          ELSE '' END                                        AS PAY_RECEIVE_FLAG --'P' bank pay, 'R' bank rec
    ,PAYMENT.SETTLE_DATE                                     AS SETL_DT
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NULL THEN COALESCE(PAYMENT.PAY_CURRENCY_CODE, PAYMENT.RECEIVE_CURRENCY_CODE) END AS SETL_CCY
    --[Amended by Jing on 23Jun2022 begin hot fix to long term fix
    --,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NULL THEN COALESCE(PAYMENT.PAY_AMOUNT,PAYMENT.RECEIVE_AMOUNT,0) END AS SETL_AMT
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NULL THEN COALESCE(PAYMENT.PAY_AMOUNT,PAYMENT.RECEIVE_AMOUNT,0) ELSE 0 END AS SETL_AMT
    --Amended by Jing on 23Jun2022 end]
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN PAYMENT.RECEIVE_CURRENCY_CODE END AS BUY_CCY
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN COALESCE(PAYMENT.RECEIVE_AMOUNT,0) END AS BUY_AMT
    ,CLIENT_PAYMENT.RECEIVE_MARK_SETTLE_DATE                 AS MRK_RECV_SETL_DT
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN PAYMENT.PAY_CURRENCY_CODE END AS SELL_CCY
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN COALESCE(PAYMENT.PAY_AMOUNT,0) END AS SELL_AMT
    ,CLIENT_PAYMENT.PAY_MARK_SETTLE_DATE                     AS MRK_PAY_SETL_DT
    ,PAYMENT.BANK_DEAL_NUMBER                                AS CROS_DEAL_NUM
    ,PAYMENT.BANK_DEAL_SUB_NUMBER                            AS CROS_DEAL_SB_NUM
    ,CASE WHEN PAYMENT.FX_DEAL_NUMBER IS NOT NULL THEN '51'
          WHEN CLIENT_PAYMENT.SHARE_DEAL_NUMBER IS NOT NULL THEN '76'
          WHEN (CLIENT_PAYMENT.PAY_DEAL_NUMBER IS NOT NULL OR CLIENT_PAYMENT.RECEIVE_DEAL_NUMBER IS NOT NULL) THEN '04'
          ELSE ''
     END                                                     AS LINK_DEAL_TYPE --TBC no share_deal_num in bank_payment
    ,COALESCE(PAYMENT.FX_DEAL_NUMBER,CLIENT_PAYMENT.SHARE_DEAL_NUMBER) AS LINK_DEAL_NUMBER
    ,COALESCE(PAYMENT.FX_DEAL_SUB_NUMBER,CLIENT_PAYMENT.SHARE_DEAL_SUB_NUMBER) AS LINK_DEAL_SUB_NUMBER
    ,PAYMENT.CREATE_TIMESTAMP                                AS CREAT_TS
    ,PAYMENT.REVERSE_TIMESTAMP                               AS RVRSE_TS
    ,PAYMENT.UPDATE_TIMESTAMP                                AS UPDT_TS
    ,PAYMENT.PAY_OUR_NOSTRO_NUMBER AS PAY_OUR_NOSTRO_NUMBER -- DB2_SYNTAX_FIX: qualified OCR-unqualified column
    ,PAYMENT.RECEIVE_OUR_NOSTRO_NUMBER AS RECEIVE_OUR_NOSTRO_NUMBER -- DB2_SYNTAX_FIX: qualified OCR-unqualified column
    ,PAYMENT.PAY_THEIR_NOSTRO_NUMBER AS PAY_THEIR_NOSTRO_NUMBER -- DB2_SYNTAX_FIX: qualified OCR-unqualified column
    ,PAYMENT.RECEIVE_THEIR_NOSTRO_NUMBER AS RECEIVE_THEIR_NOSTRO_NUMBER -- DB2_SYNTAX_FIX: qualified OCR-unqualified column
FROM FOS.NMEMO_BANK_PAYMENT PAYMENT --PRIMARY KEY (FIXING_DATE, FIXING_EVENT_TYPE, NMEMO_BANK_DEAL_NUMBER, NMEMO_BANK_DEAL_SUB_NUMBER)
JOIN FOS.NMEMO_BROKER_DEAL DEAL --primary key (NMEMO_BROKER_NUMBER, DEAL_NUMBER, NMEMO_ISSUE_CODE, DEAL_TRANSACTION_TYPE)
    ON PAYMENT.BROKER_NUMBER = DEAL.NMEMO_BROKER_NUMBER
   AND PAYMENT.BANK_DEAL_NUMBER = DEAL.DEAL_NUMBER
   AND PAYMENT.BANK_DEAL_SUB_NUMBER = DEAL.DEAL_SUB_NUMBER
   AND PAYMENT.NMEMO_ISSUE_CODE = DEAL.NMEMO_ISSUE_CODE
JOIN FOS.NMEMO_PAYMENT CLIENT_PAYMENT --PRIMARY KEY (CUSTOMER_NUMBER, SUB_ACCOUNT_NUMBER, PRODUCT_TYPE, DEAL_NUMBER, DEAL_SUB_NUMBER, FIXING_DATE, FIXING_EVENT_TYPE)
    ON CLIENT_PAYMENT.NMEMO_BANK_DEAL_NUMBER = PAYMENT.NMEMO_BANK_DEAL_NUMBER
   AND CLIENT_PAYMENT.NMEMO_BANK_DEAL_SUB_NUMBER = PAYMENT.NMEMO_BANK_DEAL_SUB_NUMBER
JOIN FOS.NMEMO_TEMPLATE NMEMO_TEMPLATE
    ON NMEMO_TEMPLATE.NMEMO_ISSUE_CODE = DEAL.NMEMO_ISSUE_CODE
LEFT JOIN FOS.NMEMO_LEG_UNDERLYING NLU
    ON NMEMO_TEMPLATE.NMEMO_ISSUE_CODE = NLU.NMEMO_ISSUE_CODE
   AND NLU.UNDERLYING_CLASS_CODE = 'IR'
   AND NLU.UNDERLYING_ISSUE_CODE = 'FIX'
JOIN (
    SELECT ROW_NUMBER() OVER (
               PARTITION BY BROKER_NUMBER,BANK_DEAL_NUMBER,BANK_DEAL_SUB_NUMBER,CREATE_DATE
               ORDER BY FIXING_DATE DESC, COALESCE(REMAINING_SETTLEMENT_NOTIONAL,0) ASC, FIXING_EVENT_TYPE
           ) AS ROW_NUM,
           NMEMO_BANK_DEAL_NUMBER,NMEMO_BANK_DEAL_SUB_NUMBER,BROKER_NUMBER,BANK_DEAL_NUMBER,FIXING_DATE,FIXING_EVENT_TYPE,CREATE_DATE -- DB2_SYNTAX_FIX: removed duplicate FIXING_DATE from OCR
    FROM FOS.NMEMO_BANK_PAYMENT
    WHERE REVERSE_TIMESTAMP IS NULL
      AND CREATE_DATE > FIXING_DATE
      AND STATUS_FLAG IN ('CONFIRMED','PREV')
) FIXING --handle sameday multiple fixing
    ON PAYMENT.FIXING_DATE = FIXING.FIXING_DATE
   AND PAYMENT.FIXING_EVENT_TYPE = FIXING.FIXING_EVENT_TYPE
   AND PAYMENT.NMEMO_BANK_DEAL_NUMBER = FIXING.NMEMO_BANK_DEAL_NUMBER
   AND PAYMENT.NMEMO_BANK_DEAL_SUB_NUMBER = FIXING.NMEMO_BANK_DEAL_SUB_NUMBER
   AND FIXING.ROW_NUM = 1
WHERE PAYMENT.ACTIVE_FLAG = 'A'
  AND NMEMO_TEMPLATE.ACTIVE_FLAG = 'A'
  AND PAYMENT.STATUS_FLAG IN ('CONFIRMED','PREV');

CALL INTERFACE.PR_PROCEDURE_LOG('GENERIC_MEMO_TRANSFORM', ld_procedure_name, 'INFO', 'End insert data to INTERFACE.GM_COMMON_FIXING_DEAL');

end

@

