
CREATE PROCEDURE INTERFACE.PR_TRANSFORM_GM_COMMON_DEAL_EXT()
-- DB2_SYNTAX_FIX: added empty parameter list for no-argument procedure.
SPECIFIC PR_TRANSFORM_GM_COMMON_DEAL_EXT
LANGUAGE SQL


BEGIN

    DECLARE SQLCODE             INT DEFAULT 0;
    DECLARE ld_message_text     VARCHAR(512);
    DECLARE ld_err_pos          VARCHAR(1000);
    DECLARE ld_error_message    VARCHAR(512);
    DECLARE ld_procedure_name   VARCHAR(100) DEFAULT 'INTERFACE.PR_TRANSFORM_GM_COMMON_DEAL_EXT';
    DECLARE ls_local_ccy_code   VARCHAR(3);
    DECLARE ls_region_code      VARCHAR(3);
    DECLARE ld_biz_date         DATE;

    -- Exception handling when there is error
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS EXCEPTION 1 ld_message_text = MESSAGE_TEXT;

        -- if SQLSTATE = 57011(transaction log for the database is full), cannot update or insert until commit.
        COMMIT;
        VALUES (ld_procedure_name || ' failed. ' || ld_err_pos || '. Details:' || ld_message_text) INTO ld_error_message;
        IF (SUBSTR(ld_message_text, 1, 8) <> 'SQL0438N') THEN -- DB2_SYNTAX_FIX: normalized not-equal operator
            CALL INTERFACE.PR_PROCEDURE_LOG('GENERIC_MEMO_TRANSFORM', ld_procedure_name, 'ERROR', ld_error_message);
            commit;
        END IF;
        RESIGNAL SQLSTATE '88888';
    END;

    CALL INTERFACE.PR_PROCEDURE_LOG('GENERIC_MEMO_TRANSFORM', ld_procedure_name, 'INFO', 'Start insert data to INTERFACE.GM_COMMON_DEAL_EXT');

    SELECT REGION_CDE INTO ls_region_code FROM INTERFACE.SYS WHERE SYS_CDE = 'EFOS';

    SET ls_local_ccy_code = INTERFACE.FN_GET_LOCAL_CURRENCY();
    SET ld_biz_date = INTERFACE.FN_GET_CURRENT_BUSINESS_DATE();

    IF EXISTS ( SELECT 1 FROM INTERFACE.GM_COMMON_DEAL_EXT FETCH FIRST 1 ROW ONLY ) THEN
        DELETE FROM INTERFACE.GM_COMMON_DEAL_EXT;
    END IF;

    SET ld_err_pos = 'Position: insert client data to INTERFACE.GM_COMMON_DEAL_EXT ';
    INSERT INTO INTERFACE.GM_COMMON_DEAL_EXT -- primary key (DEAL_NUM,CUST_NUM,SB_ACCT_NUM,DEAL_SB_NUM,PROD_TYPE,ASSET_CLASS)
    (
        ACTV_FLAG
        ,DEAL_NUM
        ,DEAL_SB_NUM
        ,DEAL_COMP_CDE
        ,DEAL_BRNCH_CDE
        ,DEAL_TRAN_TYPE
        ,CUST_NUM
        ,SB_ACCT_NUM
        ,DEAL_TYPE
        ,PROD_TYPE
        ,ASSET_CLASS
        ,GROS_SETL_FLAG
        ,PAY_INT_RATE_CDE
        ,RECV_INT_RATE_CDE
        ,PAY_UNDL_CCY_CDE --Added by Nancy on 28Dec2020
        ,RECV_UNDL_CCY_CDE --Added by Nancy on 28Dec2020
        ,PAY_INT_CAL_METH
        ,RECV_INT_CAL_METH
        ,PAY_MRGN_INT_RATE
        ,RECV_MRGN_INT_RATE
        ,PAY_RATE_FIXING_FREQUENCY
        ,RECV_RATE_FIXING_FREQUENCY
        ,PAY_NXT_RT_FIXING_DT
        ,RECV_NXT_RT_FIXING_DT
        ,PAY_SETL_FREQ
        ,RECV_SETL_FREQ
        ,PAY_NEXT_SETL_DT
        ,RECV_NEXT_SETL_DT
        ,SCH_START_DATE
        ,SCH_END_DATE
        ,PERIOD_NUMBER
    )
    SELECT
        DISTINCT
        ND.ACTIVE_FLAG                                      AS ACTV_FLAG
        ,ND.DEAL_NUMBER                                     AS DEAL_NUM
        ,ND.DEAL_SUB_NUMBER                                 AS DEAL_SB_NUM
        ,ND.DEAL_COMPANY_CODE                               AS DEAL_COMP_CDE
        ,ND.DEAL_BRANCH_CODE                                AS DEAL_BRNCH_CDE
        ,CASE WHEN ND.DEAL_TRANSACTION_TYPE = 'O' THEN 'S' ELSE 'P' END AS DEAL_TRAN_TYPE -- ND.CONSIDERATION_AMOUNT > 0 client rec premium,client sell, <0 client pay premium, client buy
        ,ND.CUSTOMER_NUMBER                                 AS CUST_NUM
        ,ND.SUB_ACCOUNT_NUMBER                              AS SB_ACCT_NUM
        ,'MM'                                               AS PROD_TYPE
        ,'MM'                                               AS DEAL_TYPE
        --,CASE WHEN NT.ASSET_TYPE IN ('FX','EQ','FI','IR','CD') THEN NT.ASSET_TYPE
        ,CASE WHEN NT.ASSET_TYPE IN ('FX','EQ','FI','IR','CT') THEN NT.ASSET_TYPE --Amend by Allen on 23Oct2020
              WHEN NT.ASSET_TYPE IN ('NX') THEN 'EQ'
              WHEN NT.ASSET_TYPE IN ('CD') THEN 'CT' --Add by Allen on 23Oct2020
              ELSE 'MX'
         END                                                AS ASSET_CLASS
        ,'0'                                                AS GROS_SETL_FLAG
        ,CASE WHEN LENGTH(TRIM(NLUPAY.UNDERLYING_ISSUE_CODE)) > 4 THEN SUBSTR(NLUPAY.UNDERLYING_ISSUE_CODE,1,2)||RIGHT(NLUPAY.UNDERLYING_ISSUE_CODE,2) ELSE NLUPAY.UNDERLYING_ISSUE_CODE END AS PAY_INT_RATE_CDE --?
        ,CASE WHEN LENGTH(TRIM(NLUREC.UNDERLYING_ISSUE_CODE)) > 4 THEN SUBSTR(NLUREC.UNDERLYING_ISSUE_CODE,1,2)||RIGHT(NLUREC.UNDERLYING_ISSUE_CODE,2) ELSE NLUREC.UNDERLYING_ISSUE_CODE END AS RECV_INT_RATE_CDE --?
        ,NLUPAY.UNDERLYING_CURRENCY_CODE                    AS PAY_UNDL_CCY_CDE --Added by Nancy on 28Dec2020
        ,NLUREC.UNDERLYING_CURRENCY_CODE                    AS RECV_UNDL_CCY_CDE --Added by Nancy on 28Dec2020
        ,'1'                                                AS PAY_INT_CAL_METH --TO DO?
        ,'1'                                                AS RECV_INT_CAL_METH --TO DO?
        ,CASE WHEN TRIM(NLUPAY.UNDERLYING_ISSUE_CODE) = 'FIX' THEN NLUPAY.UNDERLYING_INITIAL_SPOT ELSE 0 END AS PAY_MRGN_INT_RATE
        ,CASE WHEN TRIM(NLUREC.UNDERLYING_ISSUE_CODE) = 'FIX' THEN NLUREC.UNDERLYING_INITIAL_SPOT ELSE 0 END AS RECV_MRGN_INT_RATE
        ,CASE --WHEN NLFSEXTPAY.FREQUENCY = 'MONTHLY'      THEN 1    --Amended by Loiter on 22Jan2021
              --WHEN NLFSEXTPAY.FREQUENCY = 'QUARTERLY'    THEN 3    --Amended by Loiter on 22Jan2021
              --WHEN NLFSEXTPAY.FREQUENCY = 'SEMI-ANNUALLY' THEN 6   --Amended by Loiter on 22Jan2021
              --WHEN NLFSEXTPAY.FREQUENCY = 'ANNUALLY'     THEN 12   --Amended by Loiter on 22Jan2021
              WHEN NLFSEXTPAY.FREQUENCY = 'MONTHLY'        THEN '1'
              WHEN NLFSEXTPAY.FREQUENCY = 'QUARTERLY'      THEN '3'
              WHEN NLFSEXTPAY.FREQUENCY = 'SEMI-ANNUALLY'  THEN '6'
              WHEN NLFSEXTPAY.FREQUENCY = 'ANNUALLY'       THEN 'A'
              --ELSE 0 END
              ELSE '0' END                                  AS PAY_RATE_FIXING_FREQUENCY --Amended by Nancy on 02Feb2021
        ,CASE --WHEN NLFSEXTREC.FREQUENCY = 'MONTHLY'      THEN 1    --Amended by Loiter on 22Jan2021
              --WHEN NLFSEXTREC.FREQUENCY = 'QUARTERLY'    THEN 3    --Amended by Loiter on 22Jan2021
              --WHEN NLFSEXTREC.FREQUENCY = 'SEMI-ANNUALLY' THEN 6   --Amended by Loiter on 22Jan2021
              --WHEN NLFSEXTREC.FREQUENCY = 'ANNUALLY'     THEN 12   --Amended by Loiter on 22Jan2021
              WHEN NLFSEXTREC.FREQUENCY = 'MONTHLY'        THEN '1'
              WHEN NLFSEXTREC.FREQUENCY = 'QUARTERLY'      THEN '3'
              WHEN NLFSEXTREC.FREQUENCY = 'SEMI-ANNUALLY'  THEN '6'
              WHEN NLFSEXTREC.FREQUENCY = 'ANNUALLY'       THEN 'A'
              --ELSE 0 END
              ELSE '0' END                                  AS REC_RATE_FIXING_FREQUENCY --Amended by Nancy on 02Feb2021
        ,NLFSPAY.END_DATE                                   AS PAY_NXT_RT_FIXING_DT
        ,NLFSREC.END_DATE                                   AS RECV_NXT_RT_FIXING_DT
        --,COALESCE(NLFSPAY.NEXT_FIXING_DATE,NT.NMEMO_EXPIRY_DATE) AS PAY_NXT_RT_FIXING_DT --Amended by Nancy on 07Feb2021
        --,COALESCE(NLFSREC.NEXT_FIXING_DATE,NT.NMEMO_EXPIRY_DATE) AS RECV_NXT_RT_FIXING_DT --Amended by Nancy on 07Feb2021
        ,CASE WHEN NLPSEXTPAY.FREQUENCY = 'MONTHLY'         THEN 1
              WHEN NLPSEXTPAY.FREQUENCY = 'QUARTERLY'       THEN 3
              WHEN NLPSEXTPAY.FREQUENCY = 'SEMI-ANNUALLY'   THEN 6
              WHEN NLPSEXTPAY.FREQUENCY = 'ANNUALLY'        THEN 12
              ELSE 0 END                                    AS PAY_SETL_FREQ
        ,CASE WHEN NLPSEXTREC.FREQUENCY = 'MONTHLY'         THEN 1
              WHEN NLPSEXTREC.FREQUENCY = 'QUARTERLY'       THEN 3
              WHEN NLPSEXTREC.FREQUENCY = 'SEMI-ANNUALLY'   THEN 6
              WHEN NLPSEXTREC.FREQUENCY = 'ANNUALLY'        THEN 12
              ELSE 0 END                                    AS RECV_SETL_FREQ
        --,NLFSPAY.PAYMENT_DATE                              AS PAY_NEXT_SETL_DT
        --,NLFSREC.PAYMENT_DATE                              AS RECV_NEXT_SETL_DT
        --,COALESCE(NLFSPAY.START_DATE,NLFSREC.START_DATE)   AS SCH_START_DATE
        --,COALESCE(NLFSPAY.END_DATE,NLFSREC.END_DATE)       AS SCH_END_DATE --client buy fix , sell float , LEG_WEIGHT > 0 client REC,in clinet view,bank pay int
        --,COALESCE(NLFSPAY.PERIOD_NUMBER,NLFSREC.PERIOD_NUMBER) AS PERIOD_NUMBER
        ,COALESCE(NLFSPAY.NEXT_SETTLE_DATE,NT.NMEMO_EXPIRY_DATE) AS PAY_NEXT_SETL_DT --Amended by Nancy on 07Feb2021
        ,COALESCE(NLFSREC.NEXT_SETTLE_DATE,NT.NMEMO_EXPIRY_DATE) AS RECV_NEXT_SETL_DT --Amended by Nancy on 07Feb2021
        ,COALESCE(NLFSPAY.LAST_FIXING_DATE,NLFSREC.LAST_FIXING_DATE,ND.NMEMO_VALUE_DATE) AS SCH_START_DATE --Amended by Nancy on 07Feb2021
        ,COALESCE(NLFSPAY.NEXT_FIXING_DATE,NLFSREC.NEXT_FIXING_DATE,NT.NMEMO_EXPIRY_DATE) AS SCH_END_DATE --Amended by Nancy on 07Feb2021
        ,0                                                  AS PERIOD_NUMBER --Amended by Nancy on 07Feb2021 no longer use this field
    FROM FOS.NMEMO_DEAL ND
    INNER JOIN FOS.NMEMO_TEMPLATE NT -- primary key (NMEMO_ISSUE_CODE)
        ON NT.NMEMO_ISSUE_CODE = ND.NMEMO_ISSUE_CODE
    INNER JOIN FOS.NMEMO_LEG NLPAY --PAY LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
        ON ND.NMEMO_ISSUE_CODE = NLPAY.NMEMO_ISSUE_CODE
       AND NLPAY.LEG_WEIGHT > 0
    INNER JOIN FOS.NMEMO_LEG NLREC --REC LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
        ON ND.NMEMO_ISSUE_CODE = NLREC.NMEMO_ISSUE_CODE
       AND NLREC.LEG_WEIGHT < 0
    INNER JOIN FOS.NMEMO_LEG_UNDERLYING NLUPAY --PAY LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER,UNDERLYING_ISSUE_CODE,EFFECTIVE_DATE)
        ON NLPAY.NMEMO_ISSUE_CODE = NLUPAY.NMEMO_ISSUE_CODE
       AND NLPAY.NMEMO_LEG_NUMBER = NLUPAY.NMEMO_LEG_NUMBER
    INNER JOIN FOS.NMEMO_LEG_UNDERLYING NLUREC --REC LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER,UNDERLYING_ISSUE_CODE,EFFECTIVE_DATE)
        ON NLREC.NMEMO_ISSUE_CODE = NLUREC.NMEMO_ISSUE_CODE
       AND NLREC.NMEMO_LEG_NUMBER = NLUREC.NMEMO_LEG_NUMBER
    --INNER JOIN FOS.NMEMO_LEG_FIXING_SCHEDULE NLFSPAY --PAY LEG --primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER,PERIOD_NUMBER) --Amended by Nancy on 01Dec 2020
    /*INNER JOIN (SELECT * FROM
    (
        SELECT ROW_NUMBER() OVER (PARTITION BY NMEMO_ISSUE_CODE, NMEMO_LEG_NUMBER ORDER BY END_DATE ASC) AS ROW_NUM, A.* FROM FOS.NMEMO_LEG_FIXING_SCHEDULE A WHERE END_DATE >= ld_biz_date
        UNION
        SELECT ROW_NUMBER() OVER (PARTITION BY NMEMO_ISSUE_CODE, NMEMO_LEG_NUMBER ORDER BY END_DATE DESC) AS ROW_NUM, FINAL_PERIOD.* FROM FOS.NMEMO_LEG_FIXING_SCHEDULE FINAL_PERIOD WHERE END_DATE < ld_biz_date
            AND (FINAL_PERIOD.NMEMO_ISSUE_CODE,'N') IN (SELECT ND.NMEMO_ISSUE_CODE, GCD.FINAL_FIXING_FLAG FROM INTERFACE.GM_COMMON_DEAL GCD,FOS.NMEMO_DEAL ND
                                                        WHERE GCD.DEAL_NUM = ND.DEAL_NUMBER
                                                          AND GCD.CUST_NUM = ND.CUSTOMER_NUMBER
                                                          AND GCD.SB_ACCT_NUM = ND.SUB_ACCOUNT_NUMBER
                                                          AND GCD.DEAL_SB_NUM = ND.DEAL_SUB_NUMBER
                                                          AND GCD.TEMPLATE_ISSUE_CODE = ND.NMEMO_ISSUE_CODE
                                                          AND GCD.ASSET_CLASS = 'IR')
            AND NOT EXISTS (SELECT 1 FROM FOS.NMEMO_LEG_FIXING_SCHEDULE A WHERE A.END_DATE >= ld_biz_date AND FINAL_PERIOD.NMEMO_ISSUE_CODE = A.NMEMO_ISSUE_CODE AND FINAL_PERIOD.NMEMO_LEG_NUMBER = A.NMEMO_LEG_NUMBER )
    )
    WHERE ROW_NUM = 1) NLFSPAY --Keep data for one period
    ON NLFSPAY.NMEMO_ISSUE_CODE = NLPAY.NMEMO_ISSUE_CODE
    AND NLFSPAY.NMEMO_LEG_NUMBER = NLPAY.NMEMO_LEG_NUMBER*/

    -- SUPPLEMENTED/DB2_SYNTAX_FIX: rebuilt the missing / malformed client fixing-date joins (screenshots around lines 218-238) into valid DB2 nested-table syntax.
    LEFT JOIN (
        SELECT *
        FROM (
            SELECT ROW_NUMBER() OVER (
                       PARTITION BY CUSTOMER_NUMBER,SUB_ACCOUNT_NUMBER,DEAL_NUMBER,DEAL_SUB_NUMBER,NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER
                       ORDER BY NEXT_FIXING_DATE DESC
                   ) AS ROW_NUM,
                   A.*
            FROM FOS.NMEMO_FIXING_DATE_DETAIL_EXT A
        ) AS X
        WHERE ROW_NUM = 1
    ) NLFSPAY --Keep data for one period
        ON NLFSPAY.CUSTOMER_NUMBER = ND.CUSTOMER_NUMBER
       AND NLFSPAY.SUB_ACCOUNT_NUMBER = ND.SUB_ACCOUNT_NUMBER
       AND NLFSPAY.DEAL_NUMBER = ND.DEAL_NUMBER
       AND NLFSPAY.DEAL_SUB_NUMBER = ND.DEAL_SUB_NUMBER
       AND NLFSPAY.NMEMO_ISSUE_CODE = NLPAY.NMEMO_ISSUE_CODE
       AND NLFSPAY.NMEMO_LEG_NUMBER = NLPAY.NMEMO_LEG_NUMBER
    INNER JOIN FOS.NMEMO_LEG_FIXING_SCHEDULE_EXT NLFSEXTPAY --PAY LEG -- primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
        ON NLUPAY.NMEMO_ISSUE_CODE = NLFSEXTPAY.NMEMO_ISSUE_CODE --Amended by Nancy on 07Feb2021
       AND NLUPAY.NMEMO_LEG_NUMBER = NLFSEXTPAY.NMEMO_LEG_NUMBER --Amended by Nancy on 07Feb2021
    -- SUPPLEMENTED/DB2_SYNTAX_FIX: legacy FOS.NMEMO_LEG_FIXING_SCHEDULE join was visible only as a commented block; kept inactive by using current *_EXT join below.
    LEFT JOIN (
        SELECT *
        FROM (
            SELECT ROW_NUMBER() OVER (
                       PARTITION BY CUSTOMER_NUMBER,SUB_ACCOUNT_NUMBER,DEAL_NUMBER,DEAL_SUB_NUMBER,NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER
                       ORDER BY NEXT_FIXING_DATE DESC
                   ) AS ROW_NUM,
                   A.*
            FROM FOS.NMEMO_FIXING_DATE_DETAIL_EXT A
        ) AS X
        WHERE ROW_NUM = 1
    ) NLFSREC --Keep data for one period
        ON NLFSREC.CUSTOMER_NUMBER = ND.CUSTOMER_NUMBER
       AND NLFSREC.SUB_ACCOUNT_NUMBER = ND.SUB_ACCOUNT_NUMBER
       AND NLFSREC.DEAL_NUMBER = ND.DEAL_NUMBER
       AND NLFSREC.DEAL_SUB_NUMBER = ND.DEAL_SUB_NUMBER
       AND NLFSREC.NMEMO_ISSUE_CODE = NLREC.NMEMO_ISSUE_CODE
       AND NLFSREC.NMEMO_LEG_NUMBER = NLREC.NMEMO_LEG_NUMBER
    INNER JOIN FOS.NMEMO_LEG_FIXING_SCHEDULE_EXT NLFSEXTREC --REC LEG -- primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
        ON NLUREC.NMEMO_ISSUE_CODE = NLFSEXTREC.NMEMO_ISSUE_CODE --Amended by Nancy on 07Feb2021
       AND NLUREC.NMEMO_LEG_NUMBER = NLFSEXTREC.NMEMO_LEG_NUMBER --Amended by Nancy on 07Feb2021
    INNER JOIN FOS.NMEMO_LEG_PAYMENT_SCHEDULE_EXT NLPSEXTPAY --PAY LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
        ON NLUPAY.NMEMO_ISSUE_CODE = NLPSEXTPAY.NMEMO_ISSUE_CODE --Amended by Nancy on 07Feb2021
       AND NLUPAY.NMEMO_LEG_NUMBER = NLPSEXTPAY.NMEMO_LEG_NUMBER --Amended by Nancy on 07Feb2021
    INNER JOIN FOS.NMEMO_LEG_PAYMENT_SCHEDULE_EXT NLPSEXTREC --REC LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
        ON NLUREC.NMEMO_ISSUE_CODE = NLPSEXTREC.NMEMO_ISSUE_CODE --Amended by Nancy on 07Feb2021
       AND NLUREC.NMEMO_LEG_NUMBER = NLPSEXTREC.NMEMO_LEG_NUMBER --Amended by Nancy on 07Feb2021
    WHERE ND.ACTIVE_FLAG = 'A' AND NT.ACTIVE_FLAG = 'A' AND ND.DEAL_TRANSACTION_TYPE IN ('O','C') AND NT.ASSET_TYPE = 'IR';

-- broker side
SET ld_err_pos = 'Position: insert into INTERFACE.GM_COMMON_DEAL_EXT for broker';
INSERT INTO INTERFACE.GM_COMMON_DEAL_EXT
(
    ACTV_FLAG
    ,DEAL_NUM
    ,DEAL_SB_NUM
    ,DEAL_COMP_CDE
    ,DEAL_BRNCH_CDE
    ,DEAL_TRAN_TYPE
    ,CUST_NUM
    ,SB_ACCT_NUM
    ,DEAL_TYPE
    ,PROD_TYPE
    ,ASSET_CLASS
    ,GROS_SETL_FLAG
    ,PAY_INT_RATE_CDE
    ,RECV_INT_RATE_CDE
    ,PAY_UNDL_CCY_CDE --Added by Nancy on 28Dec2020
    ,RECV_UNDL_CCY_CDE --Added by Nancy on 28Dec2020
    ,PAY_INT_CAL_METH
    ,RECV_INT_CAL_METH
    ,PAY_MRGN_INT_RATE
    ,RECV_MRGN_INT_RATE
    ,PAY_RATE_FIXING_FREQUENCY
    ,RECV_RATE_FIXING_FREQUENCY
    ,PAY_NXT_RT_FIXING_DT
    ,RECV_NXT_RT_FIXING_DT
    ,PAY_SETL_FREQ
    ,RECV_SETL_FREQ
    ,PAY_NEXT_SETL_DT
    ,RECV_NEXT_SETL_DT
    ,SCH_START_DATE
    ,SCH_END_DATE
    ,PERIOD_NUMBER
)
SELECT
    DISTINCT
    BROKER_ND.ACTIVE_FLAG                                AS ACTV_FLAG
    ,BROKER_ND.DEAL_NUMBER                               AS DEAL_NUM
    ,0                                                   AS DEAL_SB_NUM
    ,CASE WHEN ls_region_code = 'SG' THEN '68' WHEN ls_region_code = 'HK' THEN '63' END
                                                         AS DEAL_COMP_CDE
    ,CASE WHEN ls_region_code = 'SG' THEN
        CASE WHEN ls_local_ccy_code = NT.SETTLEMENT_CURRENCY THEN '02' ELSE '03' END
        WHEN ls_region_code = 'HK' THEN '02' END         AS DEAL_BRNCH_CDE
    ,CASE WHEN BROKER_ND.DEAL_TRANSACTION_TYPE = 'O' THEN 'P' ELSE 'S' END
                                                         AS DEAL_TRAN_TYPE --bank view CONSIDERATION_AMOUNT < 0 --bank pay , bank purchase
    ,BROKER_ND.NMEMO_BROKER_NUMBER                       AS CUST_NUM
    ,'0001'                                              AS SB_ACCT_NUM
    ,'MM'                                                AS PROD_TYPE
    ,'MM'                                                AS DEAL_TYPE
    --,CASE WHEN NT.ASSET_TYPE IN ('FX','EQ','FI','IR','CD') THEN NT.ASSET_TYPE
    ,CASE WHEN NT.ASSET_TYPE IN ('FX','EQ','FI','IR','CT') THEN NT.ASSET_TYPE --Amend by Allen on 23Oct2020
          WHEN NT.ASSET_TYPE IN ('NX') THEN 'EQ'
          WHEN NT.ASSET_TYPE IN ('CD') THEN 'CT' --Add by Allen on 23Oct2020
          ELSE 'MX' END                                  AS ASSET_CLASS
    ,'0'                                                 AS GROS_SETL_FLAG
    ,CASE WHEN LENGTH(TRIM(NLUPAY.UNDERLYING_ISSUE_CODE)) > 4 THEN SUBSTR(NLUPAY.UNDERLYING_ISSUE_CODE,1,2)||RIGHT(NLUPAY.UNDERLYING_ISSUE_CODE,2) ELSE NLUPAY.UNDERLYING_ISSUE_CODE END AS PAY_INT_RATE_CDE --?
    ,CASE WHEN LENGTH(TRIM(NLUREC.UNDERLYING_ISSUE_CODE)) > 4 THEN SUBSTR(NLUREC.UNDERLYING_ISSUE_CODE,1,2)||RIGHT(NLUREC.UNDERLYING_ISSUE_CODE,2) ELSE NLUREC.UNDERLYING_ISSUE_CODE END AS RECV_INT_RATE_CDE --?
    ,NLUPAY.UNDERLYING_CURRENCY_CODE                     AS PAY_UNDL_CCY_CDE --Added by Nancy on 28Dec2020
    ,NLUREC.UNDERLYING_CURRENCY_CODE                     AS RECV_UNDL_CCY_CDE --Added by Nancy on 28Dec2020
    ,'1'                                                 AS PAY_INT_CAL_METH --TO DO?
    ,'1'                                                 AS RECV_INT_CAL_METH --TO DO?
    ,CASE WHEN TRIM(NLUPAY.UNDERLYING_ISSUE_CODE) = 'FIX' THEN NLUPAY.UNDERLYING_INITIAL_SPOT ELSE 0 END AS PAY_MRGN_INT_RATE
    ,CASE WHEN TRIM(NLUREC.UNDERLYING_ISSUE_CODE) = 'FIX' THEN NLUREC.UNDERLYING_INITIAL_SPOT ELSE 0 END AS RECV_MRGN_INT_RATE
    ,CASE --WHEN NLFSEXTPAY.FREQUENCY = 'MONTHLY' THEN 1      --Amended by Loiter on 22Jan2021
          --WHEN NLFSEXTPAY.FREQUENCY = 'QUARTERLY' THEN 3    --Amended by Loiter on 22Jan2021
          --WHEN NLFSEXTPAY.FREQUENCY = 'SEMI-ANNUALLY' THEN 6 --Amended by Loiter on 22Jan2021
          --WHEN NLFSEXTPAY.FREQUENCY = 'ANNUALLY' THEN 12    --Amended by Loiter on 22Jan2021
          WHEN NLFSEXTPAY.FREQUENCY = 'MONTHLY' THEN '1'
          WHEN NLFSEXTPAY.FREQUENCY = 'QUARTERLY' THEN '3'
          WHEN NLFSEXTPAY.FREQUENCY = 'SEMI-ANNUALLY' THEN '6'
          WHEN NLFSEXTPAY.FREQUENCY = 'ANNUALLY' THEN 'A'
          --ELSE 0 END
          ELSE '0' END                                  AS PAY_RATE_FIXING_FREQUENCY --Amended by Nancy on 02Feb2021
    ,CASE --WHEN NLFSEXTREC.FREQUENCY = 'MONTHLY' THEN 1       --Amended by Loiter on 22Jan2021
          --WHEN NLFSEXTREC.FREQUENCY = 'QUARTERLY' THEN 3     --Amended by Loiter on 22Jan2021
          --WHEN NLFSEXTREC.FREQUENCY = 'SEMI-ANNUALLY' THEN 6 --Amended by Loiter on 22Jan2021
          --WHEN NLFSEXTREC.FREQUENCY = 'ANNUALLY' THEN 12     --Amended by Loiter on 22Jan2021
          WHEN NLFSEXTREC.FREQUENCY = 'MONTHLY' THEN '1'
          WHEN NLFSEXTREC.FREQUENCY = 'QUARTERLY' THEN '3'
          WHEN NLFSEXTREC.FREQUENCY = 'SEMI-ANNUALLY' THEN '6'
          WHEN NLFSEXTREC.FREQUENCY = 'ANNUALLY' THEN 'A'
          --ELSE 0 END
          ELSE '0' END                                  AS RECV_RATE_FIXING_FREQUENCY --Amended by Nancy on 02Feb2021
    --,NLFSPAY.END_DATE                                  AS PAY_NXT_RT_FIXING_DT
    --,NLFSREC.END_DATE                                  AS RECV_NXT_RT_FIXING_DT
    ,COALESCE(NLFSPAY.NEXT_FIXING_DATE,NT.NMEMO_EXPIRY_DATE)
                                                         AS PAY_NXT_RT_FIXING_DT --Amended by Nancy on 07Feb2021
    ,COALESCE(NLFSREC.NEXT_FIXING_DATE,NT.NMEMO_EXPIRY_DATE)
                                                         AS RECV_NXT_RT_FIXING_DT --Amended by Nancy on 07Feb2021
    ,CASE WHEN NLPSEXTPAY.FREQUENCY = 'MONTHLY' THEN 1
          WHEN NLPSEXTPAY.FREQUENCY = 'QUARTERLY' THEN 3
          WHEN NLPSEXTPAY.FREQUENCY = 'SEMI-ANNUALLY' THEN 6
          WHEN NLPSEXTPAY.FREQUENCY = 'ANNUALLY' THEN 12
          ELSE 0 END                                    AS PAY_SETL_FREQ
    ,CASE WHEN NLPSEXTREC.FREQUENCY = 'MONTHLY' THEN 1
          WHEN NLPSEXTREC.FREQUENCY = 'QUARTERLY' THEN 3
          WHEN NLPSEXTREC.FREQUENCY = 'SEMI-ANNUALLY' THEN 6
          WHEN NLPSEXTREC.FREQUENCY = 'ANNUALLY' THEN 12
          ELSE 0 END                                    AS RECV_SETL_FREQ
    --,NLFSPAY.PAYMENT_DATE                              AS PAY_NEXT_SETL_DT
    --,NLFSREC.PAYMENT_DATE                              AS RECV_NEXT_SETL_DT
    --,COALESCE(NLFSPAY.START_DATE,NLFSREC.START_DATE)   AS SCH_START_DATE
    --,COALESCE(NLFSPAY.END_DATE,NLFSREC.END_DATE)       AS SCH_END_DATE --client buy fix , sell float , LEG_WEIGHT > 0 client REC,in clinet view,bank pay int
    --,COALESCE(NLFSPAY.PERIOD_NUMBER,NLFSREC.PERIOD_NUMBER) AS PERIOD_NUMBER -- DB2_SYNTAX_FIX: kept whole legacy expression commented
    ,COALESCE(NLFSPAY.NEXT_SETTLE_DATE,NT.NMEMO_EXPIRY_DATE)
                                                         AS PAY_NEXT_SETL_DT --Amended by Nancy on 07Feb2021
    ,COALESCE(NLFSREC.NEXT_SETTLE_DATE,NT.NMEMO_EXPIRY_DATE)
                                                         AS RECV_NEXT_SETL_DT --Amended by Nancy on 07Feb2021
    ,COALESCE(NLFSPAY.LAST_FIXING_DATE,NLFSREC.LAST_FIXING_DATE,BROKER_ND.NMEMO_VALUE_DATE)
                                                         AS SCH_START_DATE --Amended by Nancy on 07Feb2021
    ,COALESCE(NLFSPAY.NEXT_FIXING_DATE,NLFSREC.NEXT_FIXING_DATE,NT.NMEMO_EXPIRY_DATE)
                                                         AS SCH_END_DATE --Amended by Nancy on 07Feb2021
    ,0                                                   AS PERIOD_NUMBER --Amended by Nancy on 07Feb2021
FROM FOS.NMEMO_BROKER_DEAL BROKER_ND --primary key (NMEMO_BROKER_NUMBER, DEAL_NUMBER, NMEMO_ISSUE_CODE, DEAL_TRANSACTION_TYPE)
INNER JOIN FOS.NMEMO_TEMPLATE NT --primary key (NMEMO_ISSUE_CODE)
    ON NT.NMEMO_ISSUE_CODE = BROKER_ND.NMEMO_ISSUE_CODE
INNER JOIN FOS.NMEMO_LEG NLPAY --PAY LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
    ON BROKER_ND.NMEMO_ISSUE_CODE = NLPAY.NMEMO_ISSUE_CODE
   AND NLPAY.LEG_WEIGHT > 0
INNER JOIN FOS.NMEMO_LEG NLREC --REC LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
    ON BROKER_ND.NMEMO_ISSUE_CODE = NLREC.NMEMO_ISSUE_CODE
   AND NLREC.LEG_WEIGHT < 0
INNER JOIN FOS.NMEMO_LEG_UNDERLYING NLUPAY --PAY LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER,UNDERLYING_ISSUE_CODE,EFFECTIVE_DATE)
    ON NLPAY.NMEMO_ISSUE_CODE = NLUPAY.NMEMO_ISSUE_CODE
   AND NLPAY.NMEMO_LEG_NUMBER = NLUPAY.NMEMO_LEG_NUMBER
INNER JOIN FOS.NMEMO_LEG_UNDERLYING NLUREC --REC LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER,UNDERLYING_ISSUE_CODE,EFFECTIVE_DATE)
    ON NLREC.NMEMO_ISSUE_CODE = NLUREC.NMEMO_ISSUE_CODE
   AND NLREC.NMEMO_LEG_NUMBER = NLUREC.NMEMO_LEG_NUMBER
-- SUPPLEMENTED/DB2_SYNTAX_FIX: screenshots missed broker FROM/JOIN lines around 383-405; rebuilt from client pattern with BROKER_ND keys.
LEFT JOIN (
    SELECT *
    FROM (
        SELECT ROW_NUMBER() OVER (
                   PARTITION BY CUSTOMER_NUMBER,SUB_ACCOUNT_NUMBER,DEAL_NUMBER,DEAL_SUB_NUMBER,NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER
                   ORDER BY NEXT_FIXING_DATE DESC
               ) AS ROW_NUM,
               A.*
        FROM FOS.NMEMO_FIXING_DATE_DETAIL_EXT A
    ) AS X
    WHERE ROW_NUM = 1
) NLFSPAY --Keep data for one period
    ON NLFSPAY.CUSTOMER_NUMBER = BROKER_ND.NMEMO_BROKER_NUMBER
   AND NLFSPAY.SUB_ACCOUNT_NUMBER = '0001'
   AND NLFSPAY.DEAL_NUMBER = BROKER_ND.DEAL_NUMBER
   AND NLFSPAY.DEAL_SUB_NUMBER = 0
   AND NLFSPAY.NMEMO_ISSUE_CODE = NLPAY.NMEMO_ISSUE_CODE
   AND NLFSPAY.NMEMO_LEG_NUMBER = NLPAY.NMEMO_LEG_NUMBER
INNER JOIN FOS.NMEMO_LEG_FIXING_SCHEDULE_EXT NLFSEXTPAY --PAY LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
    ON NLUPAY.NMEMO_ISSUE_CODE = NLFSEXTPAY.NMEMO_ISSUE_CODE --Amended by Nancy on 07Feb2021
   AND NLUPAY.NMEMO_LEG_NUMBER = NLFSEXTPAY.NMEMO_LEG_NUMBER --Amended by Nancy on 07Feb2021
LEFT JOIN (
    SELECT *
    FROM (
        SELECT ROW_NUMBER() OVER (
                   PARTITION BY CUSTOMER_NUMBER,SUB_ACCOUNT_NUMBER,DEAL_NUMBER,DEAL_SUB_NUMBER,NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER
                   ORDER BY NEXT_FIXING_DATE DESC
               ) AS ROW_NUM,
               A.*
        FROM FOS.NMEMO_FIXING_DATE_DETAIL_EXT A
    ) AS X
    WHERE ROW_NUM = 1
) NLFSREC --Keep data for one period
    ON NLFSREC.CUSTOMER_NUMBER = BROKER_ND.NMEMO_BROKER_NUMBER
   AND NLFSREC.SUB_ACCOUNT_NUMBER = '0001'
   AND NLFSREC.DEAL_NUMBER = BROKER_ND.DEAL_NUMBER
   AND NLFSREC.DEAL_SUB_NUMBER = 0
   AND NLFSREC.NMEMO_ISSUE_CODE = NLREC.NMEMO_ISSUE_CODE
   AND NLFSREC.NMEMO_LEG_NUMBER = NLREC.NMEMO_LEG_NUMBER
INNER JOIN FOS.NMEMO_LEG_FIXING_SCHEDULE_EXT NLFSEXTREC --REC LEG --primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
    ON NLUREC.NMEMO_ISSUE_CODE = NLFSEXTREC.NMEMO_ISSUE_CODE --Amended by Nancy on 07Feb2021
   AND NLUREC.NMEMO_LEG_NUMBER = NLFSEXTREC.NMEMO_LEG_NUMBER --Amended by Nancy on 07Feb2021
INNER JOIN FOS.NMEMO_LEG_PAYMENT_SCHEDULE_EXT NLPSEXTPAY --PAY LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
    ON NLUPAY.NMEMO_ISSUE_CODE = NLPSEXTPAY.NMEMO_ISSUE_CODE --Amended by Nancy on 07Feb2021
   AND NLUPAY.NMEMO_LEG_NUMBER = NLPSEXTPAY.NMEMO_LEG_NUMBER --Amended by Nancy on 07Feb2021
INNER JOIN FOS.NMEMO_LEG_PAYMENT_SCHEDULE_EXT NLPSEXTREC --REC LEG primary key (NMEMO_ISSUE_CODE,NMEMO_LEG_NUMBER)
    ON NLUREC.NMEMO_ISSUE_CODE = NLPSEXTREC.NMEMO_ISSUE_CODE --Amended by Nancy on 07Feb2021
   AND NLUREC.NMEMO_LEG_NUMBER = NLPSEXTREC.NMEMO_LEG_NUMBER --Amended by Nancy on 07Feb2021
WHERE BROKER_ND.ACTIVE_FLAG = 'A' AND NT.ACTIVE_FLAG = 'A' AND BROKER_ND.DEAL_TRANSACTION_TYPE IN ('O','C') AND NT.ASSET_TYPE = 'IR';

CALL INTERFACE.PR_PROCEDURE_LOG('GENERIC_MEMO_TRANSFORM', ld_procedure_name, 'INFO', 'end insert data to INTERFACE.GM_COMMON_DEAL_EXT');

end

@
